config/routes.rb
Rails.application.routes.draw do
  resources :master_services
  resources :booking_details
  resources :room_details
  resources :hotel_details
  devise_for :users
  root 'hotel_details#index'  
  get 'my_bookings', to: 'users#my_bookings'
  get 'all_bookings', to: 'users#all_bookings'
  get 'services', to: 'room_details#services'
  get 'details', to: 'room_details#details'
  # get 'booking_details', to: 'users#my_booking'
end

app/models/master_service.rb
class MasterService < ApplicationRecord
  has_many :room_services
  has_many :room_details, through: :room_services
  # has_and_belongs_to_many :room_details
end

app/controllers/master_services_controller.rb
class MasterServicesController < ApplicationController
  before_action :set_master_service, only: %i[ show edit update destroy ]

  # GET /master_services or /master_services.json
  def index
    @master_services = MasterService.all
  end

  # GET /master_services/1 or /master_services/1.json
  def show
  end

  # GET /master_services/new
  def new
    @master_service = MasterService.new
  end

  # GET /master_services/1/edit
  def edit
  end

  # POST /master_services or /master_services.json
  def create
    @master_service = MasterService.new(master_service_params)

    respond_to do |format|
      if @master_service.save
        format.html { redirect_to @master_service, notice: "Master service was successfully created." }
        format.json { render :show, status: :created, location: @master_service }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @master_service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /master_services/1 or /master_services/1.json
  def update
    respond_to do |format|
      if @master_service.update(master_service_params)
        format.html { redirect_to @master_service, notice: "Master service was successfully updated." }
        format.json { render :show, status: :ok, location: @master_service }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @master_service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /master_services/1 or /master_services/1.json
  def destroy
    @master_service.destroy
    respond_to do |format|
      format.html { redirect_to master_services_url, notice: "Master service was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_master_service
      @master_service = MasterService.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def master_service_params
      params.require(:master_service).permit(:service)
    end
end

app/helpers/master_services_helper.rb
module MasterServicesHelper
end

app/views/master_services/_form.html.erb
<%= form_with(model: master_service) do |form| %>
  <% if master_service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(master_service.errors.count, "error") %> prohibited this master_service from being saved:</h2>

      <ul>
        <% master_service.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :service %>
    <%= form.text_field :service %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/master_services/edit.html.erb
<h1>Editing Master Service</h1>

<%= render 'form', master_service: @master_service %>

<%= link_to 'Show', @master_service %> |
<%= link_to 'Back', master_services_path %>

app/views/master_services/index.html.erb
<h1>Master Services</h1>

<table>
  <thead>
    <tr>
      <th>Services</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @master_services.each do |master_service| %>
      <tr>
        <td><%= master_service.service %></td>
        <td><%= link_to 'Show', master_service %></td>
        <td><%= link_to 'Edit', edit_master_service_path(master_service) %></td>
        <td><%= link_to 'Destroy', master_service, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Master Service', new_master_service_path %>

app/views/master_services/new.html.erb
<h1>New Master Service</h1>

<%= render 'form', master_service: @master_service %>

<%= link_to 'Back', master_services_path %>

app/views/master_services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Service:</strong>
  <%= @master_service.service %>
</p>

<%= link_to 'Edit', edit_master_service_path(@master_service) %> |
<%= link_to 'Back', master_services_path %>