config/routes.rb
Rails.application.routes.draw do
  resources :master_services
  resources :booking_details
  resources :room_details
  resources :hotel_details
  devise_for :users
  root 'hotel_details#index'  
  get 'my_bookings', to: 'users#my_bookings'
  get 'all_bookings', to: 'users#all_bookings'
  get 'services', to: 'room_details#services'
  get 'details', to: 'room_details#details'
  # get 'booking_details', to: 'users#my_booking'
end

app/models/hotel_detail.rb
class HotelDetail < ApplicationRecord
	has_many :room_details
	has_one_attached :main_image

	validates :hotel_name, length: { minimum: 2, maximum: 30 } , presence: true
	validates :address, length: { minimum: 7, maximum: 30 } , presence: true

end

app/controllers/hotel_details_controller.rb
class HotelDetailsController < ApplicationController
  before_action :set_hotel_detail, only: %i[ show edit update destroy ]

  # GET /hotel_details or /hotel_details.json
  def index
    @hotel_details = HotelDetail.all
  end

  # GET /hotel_details/1 or /hotel_details/1.json
  def show
    @minimum_price = @hotel_detail.room_details.minimum(:price_per).to_i
    @minimum_price_gst = (@minimum_price * 0.12).round()
    @room_details = RoomDetail.where(hotel_detail_id: params[:id])
  end

  # GET /hotel_details/new
  def new
    @hotel_detail = HotelDetail.new
  end

  # GET /hotel_details/1/edit
  def edit
  end

  # POST /hotel_details or /hotel_details.json
  def create
    @hotel_detail = HotelDetail.new(hotel_detail_params)

    respond_to do |format|
      if @hotel_detail.save
        format.html { redirect_to @hotel_detail, notice: "Hotel detail was successfully created." }
        format.json { render :show, status: :created, location: @hotel_detail }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @hotel_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hotel_details/1 or /hotel_details/1.json
  def update
    respond_to do |format|
      if @hotel_detail.update(hotel_detail_params)
        format.html { redirect_to @hotel_detail, notice: "Hotel detail was successfully updated." }
        format.json { render :show, status: :ok, location: @hotel_detail }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @hotel_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotel_details/1 or /hotel_details/1.json
  def destroy
    @hotel_detail.destroy
    respond_to do |format|
      format.html { redirect_to hotel_details_url, notice: "Hotel detail was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hotel_detail
      @hotel_detail = HotelDetail.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def hotel_detail_params
      params.require(:hotel_detail).permit(:hotel_name, :address, :main_image)
    end
end

app/helpers/hotel_details_helper.rb
module HotelDetailsHelper
end

app/views/hotel_details/_facilities.html.erb
<div class="card w-100 bg-light mb-3 facilities">
  <div class="row ">
    <div class="col-xl-2 center-div">
      <i class="fa fa-building fa-2x"></i>
    </div>
    <div class="col-xl-2 center-div">
      <i class="fa fa-cutlery fa-2x"></i>
    </div>
    <div class="col-xl-2 center-div">
      <i class="fa fa-wifi fa-2x"></i>
    </div>
    <div class="col-xl-2 center-div">
      <i class="fa fa-tv fa-2x"></i>
    </div>
    <div class="col-xl-2 center-div">
       <i class="fa fa-car fa-2x"></i>
    </div>
    <div class="col-xl-2 center-div">
       <i class="fa fa-snowflake-o fa-2x"></i>
    </div>
  </div>
</div>
<div class="card w-100 bg-light mb-3 details">
  <div class="row center-content">
    <div class="col-sm">
      City View
    </div>
    <div class="col-sm">
      BBQ Facilities
    </div>
    <div class="col-sm">
      Free Wifi
    </div>
    <div class="col-sm">
      Tv
    </div>
    <div class="col-sm">
      Free Parking
    </div>
    <div class="col-sm">
      Air Conditioning
    </div>
  </div>
</div>

app/views/hotel_details/_form.html.erb
<%= form_with(model: hotel_detail, validate: true) do |form| %>
  <% if hotel_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hotel_detail.errors.count, "error") %> prohibited this hotel_detail from being saved:</h2>

      <ul>
        <% hotel_detail.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group"> 
    <%= form.label :hotel_name %>
    <div class="row">
      <div class="col-3">
        <%= form.text_field :hotel_name ,class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :address %>
    <div class="row">
      <div class="col-3">
    <%= form.text_area :address,class: "form-control" %>
      </div>
    </div>
  </div>
  
  <div class="form-group">
    <%= form.label :main_image %>
    <div class="row">
      <div class="col-3">
        <%= form.file_field :main_image, class: "form-control-file" %>
      </div>
    </div>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/hotel_details/_rooms.html.erb
<h1>Room Details</h1>

<div class="container">
  <div class="row my-row">
    <div class="col-xl-8 my-col ">
      Rooms
    </div>
    <div class="col-xl-4 my-col">
      OPTIONS
    </div>
  </div>
  <% @room_details.each do |room_detail| %>
  <div class="row my-row-he">
    <div class="col-xl-8 my-col">
        <div class="img-container">
              <div id="carousel_<%= room_detail.id %>" class="carousel slide" data-ride="carousel">
              <div class="carousel-inner">
              <% (0...room_detail.images.count).each do |image| %>
                <div class="carousel-item <%= 'active' if image == 0 %> ">
                  <%= image_tag room_detail.images[image], style: "height:300px",class: "d-block w-100" %>
                </div>
              <% end %>
              </div>
              <a class="carousel-control-prev" href="#carousel_<%= room_detail.id %>" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="carousel-control-next" href="#carousel_<%= room_detail.id %>" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
            </div>
        </div>

      </div>
    <div class="col-xl-4 my-col">
      <div class="row">
        <div class="col-xl-6">
      </br>
      <small>Per Night</small></br>
      <i class="fa fa-inr"></i>&nbsp;<big><%= room_detail.price_per %>/-</big></br>
      &nbsp;&nbsp;<small>+<i class="fa fa-inr"></i><%= (room_detail.price_per * 0.12) %>&nbsp;taxes & fees</small></br></br>
      </div>
        <div class="col-xl-6">
          </br></br>
          <%= link_to 'Book', room_detail, class: "btn btn-success" %>
          
            <%#= link_to 'Details', services_path,  {remote: :true, 'data-toggle':  "modal", 'data-target': '#modal-window', class: 'btn btn-primary'}  %>
            <%= link_to 'Details', details_path(id: room_detail), class: 'btn btn-primary'  %>
            <div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
              <div class="modal-dialog modal-xl" role="document">
                <div class="modal-content">
                  <%#= render 'room_details/services', locals: {room: room_detail} %>
                  <%= render :partial => "room_details/services", :locals => { :room => room_detail } %>
                </div>
              </div>
            </div>
          <% if current_user && current_user.admin? %>
          <%= link_to 'Edit', edit_room_detail_path(room_detail), class: "btn btn-light" %>
          <%= link_to 'Destroy', room_detail, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-light" %>
          <% end %>
        </div>
      </div>
      <h7><i class="fa fa-times-circle-o"></i>&nbsp;Non-Refundable</h7></br>
      <h7><i class="fa fa-check-circle-o"></i>&nbsp;No meals included</h7></br></br>
       <h3><%= room_detail.room_type %> with <%= room_detail.room_view %></h3>
      <div class="row">
        <div class="col-md">
          <h7><i class="fa fa-window-maximize"></i>&nbsp;<%= (room_detail.room_size).to_i %>sq.ft</h7>
        </div>
        <div class="col-md">
          <h7><i class="fa fa-building-o"></i>&nbsp;<%= room_detail.room_view %></h7>
        </div>
        <div class="col-md">
          <h7><i class="fa fa-bed"></i>&nbsp;<%= room_detail.bed_type %></h7>
        </div>
      </div>


    </div>
  </div>
  <% end %>
</div>




<!-- <div class="container">
  <div class="row my-row">
    <div class="col-xl my-col">
      Rooms
    </div>
    <div class="col-xl my-col">
      OPTIONS
    </div>
    <div class="col-xl my-col">
      PRICE
    </div>
  </div>

  <div class="row my-row">
    <div class="col-xl ">
      <div class="row img-row">
        image
      </div>
      <div class="row desc-row">
        Description
      </div>
    </div>
    <div class="col-xl ">
      <div class="row img-row">
        image
      </div>
      <div class="row desc-row">
        Description
      </div>
    </div>
    <div class="col-xl">
      <div class="row img-row">
        image
      </div>
      <div class="row desc-row">
        Description
      </div>
    </div>
  </div>
</div> -->


<!-- <table>
  <thead>
    <tr>
      <th>Hotel detail</th>
      <th>Room type</th>
      <th>Price per</th>
      <th>Bed type</th>
      <th>Room size</th>
      <th>Room view</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @room_details.each do |room_detail| %>
      <tr>
        <td><%= room_detail.hotel_detail_id %></td>
        <td><%= room_detail.room_type %></td>
        <td><%= room_detail.price_per %></td>
        <td><%= room_detail.bed_type %></td>
        <td><%= room_detail.room_size %></td>
        <td><%= room_detail.room_view %></td>
        <td><%= link_to 'Show', room_detail %></td>
        <td><%= link_to 'Edit', edit_room_detail_path(room_detail) %></td>
        <td><%= link_to 'Destroy', room_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
 -->

app/views/hotel_details/edit.html.erb
<h1>Editing Hotel Detail</h1>

<%= render 'form', hotel_detail: @hotel_detail %>

<!-- <%= link_to 'Show', @hotel_detail %> | -->
<%= link_to 'Back', hotel_details_path %>

app/views/hotel_details/index.html.erb
<h1>Hotel Details</h1>


<% if !@hotel_details.empty? %>
<div class="container">
  <div class="row">
    <% @hotel_details.each do |hotel_detail| %>
    <div class="col-md-6 ">
<div class="card text-white bg-dark mb-3">
   <%= image_tag hotel_detail.main_image, class: "card-img-top" %>
  <div class="card-body">
    <div class="row">
      <div class="col-xl-6">
        <h5 class="card-title"><%= hotel_detail.hotel_name %></h5>
    <p class="card-text"><i class="fa fa-map-marker fa-1x"></i>&nbsp;<%= hotel_detail.address %></p>
      </div>
      <div class="col-xl-6">
        <label class="font-weight-light card-text text-right">Starting from</label></br>
    <p class="card-text"><i class="fa fa-inr fa-1x"></i>&nbsp;<%= hotel_detail.room_details.minimum(:price_per).to_i %></p>
      </div>
    </div></br>
           <div class=" card-text">
              
               <%= link_to 'Show', hotel_detail, class: "btn btn-primary" %>            
            <% if current_user && current_user.admin? %>
            <%= link_to 'Edit', edit_hotel_detail_path(hotel_detail), class: "btn btn-warning" %>
           <%= link_to 'Delete', hotel_detail, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
            </div>

  </div>
</div>
</div>
    <% end %>
  </div>
</div>
<% else %>
<h5>No hotels Available for Booking</h5>
<% end %>

app/views/hotel_details/new.html.erb
<h1>New Hotel Detail</h1>

<%= render 'form', hotel_detail: @hotel_detail %>

<%= link_to 'Back', hotel_details_path %>

app/views/hotel_details/show.html.erb
<div class="container">
  
  <div class="card bg-dark text-black">
  <%= image_tag @hotel_detail.main_image, class: "card-img" %>
  <div class="card-img-overlay">
    <h5 class="card-title"><%= @hotel_detail.hotel_name %></h5>
    <p class="card-text"><i class="fa fa-map-marker fa-1x"></i>&nbsp;<%= @hotel_detail.address %></p>
    <label class="font-weight-light">Starting from</label></br>
    <i class="fa fa-inr"></i>&nbsp;<big><%= @minimum_price %>/-</big></br>
    &nbsp;&nbsp;<small>+<i class="fa fa-inr"></i><%= @minimum_price_gst %>&nbsp;taxes & fees</small></br></br></br></br></br></br></br>
    <% if current_user && current_user.admin? %>
    <div><%= link_to 'AddRooms', new_room_detail_path(@hotel_detail), class: "btn btn-light"%> 
    <%= link_to 'Edit Hotel', edit_hotel_detail_path(@hotel_detail),class: "btn btn-light" %> </div>
    <% end %>
  </div>
</div>


<%= render 'facilities' %>

<% if !@room_details.empty? %>
<%= render 'rooms' %>
<% else %>
<h1>No Rooms Currently</h1>
<% end %>

<%= link_to 'Back', hotel_details_path %>

</div>