config/routes.rb
Rails.application.routes.draw do
  resources :master_services
  resources :booking_details
  resources :room_details
  resources :hotel_details
  devise_for :users
  root 'hotel_details#index'  
  get 'my_bookings', to: 'users#my_bookings'
  get 'all_bookings', to: 'users#all_bookings'
  get 'services', to: 'room_details#services'
  get 'details', to: 'room_details#details'
  # get 'booking_details', to: 'users#my_booking'
end

app/models/room_detail.rb
class RoomDetail < ApplicationRecord
  belongs_to :hotel_detail
  has_many :booking_details
  has_many :users, through: :booking_details
  has_many :room_services
  has_many :master_services, through: :room_services
  # has_and_belongs_to_many :master_services
  has_many_attached :images

  # SERVICES = %i[ Work_Desk Free_Wi-Fi Air_Conditioning Electric_Kettle 24-hour_Room_Service Mineral_Water Bathroom 24-hour_Housekeeping 24-hour_In-room_Dining Laundry_Service Mini_Fridge 
  #               Clothes_Rack Hairdryer TV Hot_&_Cold_Water Reading_Lamp Electronic_Safe Woollen_Blanket Dental_Kit Closet Hangers Slippers In-house_Movies Bathrobes]

  validates :room_type, length: { minimum: 5, maximum: 30 } , presence: true
  validates :price_per, numericality: { greater_than: 0 }, presence: true
  validates :bed_type, :room_view, length: { minimum: 5, maximum: 20 } , presence: true
  validates :room_size, numericality: { greater_than: 0 } , presence: true
end

app/controllers/room_details_controller.rb
class RoomDetailsController < ApplicationController
  before_action :set_room_detail, only: %i[ show edit update destroy details]

  # GET /room_details or /room_details.json
  def index
    @room_details = RoomDetail.all
  end

  # GET /room_details/1 or /room_details/1.json
  def show
    @hotel_details = @room_detail.hotel_detail
  end

  # GET /room_details/new
  def new
    hotelid = params[:format].to_i
    @room_detail = RoomDetail.new(hotel_detail_id: hotelid)
  end

  def services
    
    respond_to do |format|
      format.html
      format.js
    end
  end

  def details
    
  end

  # GET /room_details/1/edit
  def edit
  end

  # POST /room_details or /room_details.json
  def create
    ms = room_detail_params.fetch("master_services")
    room_params = room_detail_params.except("master_services")
    # byebug
    @room_detail = RoomDetail.new(room_params)
    respond_to do |format|
      if @room_detail.save

            if ms.present?
                ms.reject(&:empty?).each do |m|
                  # byebug
                RoomService.create(room_detail_id: @room_detail.id,master_service_id: m.to_i)
              end
           end

        format.html { redirect_to @room_detail, notice: "Room detail was successfully created." }
        format.json { render :show, status: :created, location: @room_detail }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /room_details/1 or /room_details/1.json
  def update
    respond_to do |format|
      if @room_detail.update(room_detail_params)
        format.html { redirect_to @room_detail, notice: "Room detail was successfully updated." }
        format.json { render :show, status: :ok, location: @room_detail }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /room_details/1 or /room_details/1.json
  def destroy
    @room_detail.destroy
    respond_to do |format|
      format.html { redirect_to hotel_details_url, notice: "Room detail was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room_detail
      @room_detail = RoomDetail.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_detail_params
      params.require(:room_detail).permit(:hotel_detail_id, :room_type, :price_per, :bed_type, :room_size, :room_view,master_services: [], images: [])
    end
end

app/helpers/room_details_helper.rb
module RoomDetailsHelper
end

app/views/room_details/_form.html.erb
<%= form_with(model: room_detail, validate: true) do |form| %>
  <% if room_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room_detail.errors.count, "error") %> prohibited this room_detail from being saved:</h2>

      <ul>
        <% room_detail.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :hotel_detail_id %>
    <div class="row">
      <div class="col-3">
    <%= form.number_field :hotel_detail_id, readonly: true %>
     </div>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :room_type %>
    <div class="row">
      <div class="col-3">
    <%= form.select :room_type, ['Junior Suite','Suite Room','Ex Deluxe Room','Ex Twin Room','Ex King Suite']  %>
     </div>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :price_per_night %>
    <div class="row">
      <div class="col-3">
    <%= form.text_field :price_per %>
     </div>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :bed_type %>
    <div class="row">
      <div class="col-3">
    <%= form.select :bed_type, ['King Bed','Double Bed','Single Bed','Twin Bed'] %>
     </div>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :room_size_in_sq_ft %>
    <div class="row">
      <div class="col-3">
    <%= form.text_field :room_size %>
     </div>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :room_view %>
    <div class="row">
      <div class="col-3">
      <%= form.select :room_view, ['City View','Mountain View','River View'] %>
     </div>
    </div>
  </div></br>

    <h6>Room Amenities</h6>
    <div class="row form-check form-check-inline">
        <%= form.collection_check_boxes :master_services, MasterService.all, :id, :service do |b| %>
        <div class="collection-check-box ">
           <div class="col-3">

         <%= b.check_box %>
         <%= b.label %>
        </div>
      </div>

        <% end %>
    </div></br></br>

    <div class="form-group">
    <%= form.label :images %>
    <div class="row">
      <div class="col-3">
        <%= form.file_field :images, multiple: true,  class: "form-control-file" %>
      </div>
    </div>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/room_details/_services.html.erb
<div class="modal-header">
  <h3 class="modal-title" id="myModalLabel"><%= room.room_type %> with <%= room.room_view %></h3>
  <button type="button" class="close" data-dismiss="modal">x</button>
  
</div>
<div class="modal-body">
  <div class="container">
    
              <div id="carousel_<%= room.id + 10 %>" class="carousel slide" data-ride="carousel">
              <div class="carousel-inner">
              <% (0...room.images.count).each do |image| %>
                <div class="carousel-item <%= 'active' if image == 0 %> ">
                  <%= image_tag room.images[image], style: "height:300px",class: "d-block w-100" %>
                </div>
              <% end %>
              </div>
              <a class="carousel-control-prev" href="#carousel_<%= room.id + 10 %>" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="carousel-control-next" href="#carousel_<%= room.id + 10 %>" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
            </div>
        </br>
        <div class="row">
        <div class="col-xl-2">
          <h7><i class="fa fa-window-maximize"></i>&nbsp;<%= (room.room_size).to_i %>sq.ft</h7>
        </div>
        <div class="col-xl-2">
          <h7><i class="fa fa-building-o"></i>&nbsp;<%= room.room_view %></h7>
        </div>
        <div class="col-xl-2">
          <h7><i class="fa fa-bed"></i>&nbsp;<%= room.bed_type %></h7>
        </div>
      </div>
</br>

<div class="div">
  <div class="row">
    <div class="col-md-12">
      <h3>Room Amenities</h3>
    </div>
    </br>
    <% room.services.each do |r|%>
    <div class="col-md-3">
      
      <h6><i class="fa fa-check-circle-o"></i>&nbsp;<%= r.gsub("_", " ") %></h6>
    </div>
    <% end %>
  </div>
</div>
                


  </div>
</div>

app/views/room_details/details.html.erb
<div class="container">
    			<h1><%= @room_detail.room_type %> with <%= @room_detail.room_view %></h1>
              <div id="carousel_<%= @room_detail.id + 10 %>" class="carousel slide" data-ride="carousel">
              <div class="carousel-inner">
              <% (0...@room_detail.images.count).each do |image| %>
                <div class="carousel-item <%= 'active' if image == 0 %> ">
                  <%= image_tag @room_detail.images[image], style: "height:350px",class: "d-block w-100" %>
                </div>
              <% end %>
              </div>
              <a class="carousel-control-prev" href="#carousel_<%= @room_detail.id + 10 %>" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="carousel-control-next" href="#carousel_<%= @room_detail.id + 10 %>" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
            </div>
        </br>
        <div class="row">
        <div class="col-xl-2">
          <h7><i class="fa fa-window-maximize"></i>&nbsp;<%= (@room_detail.room_size).to_i %>sq.ft</h7>
        </div>
        <div class="col-xl-2">
          <h7><i class="fa fa-building-o"></i>&nbsp;<%= @room_detail.room_view %></h7>
        </div>
        <div class="col-xl-2">
          <h7><i class="fa fa-bed"></i>&nbsp;<%= @room_detail.bed_type %></h7>
        </div>
      </div>
</br>

<div class="div">
  <div class="row">
    <div class="col-md-12">
      <h3>Room Amenities</h3>
    </div>
    </br>
    <% @room_detail.master_services.each do |r|%>
    <div class="col-md-3">
      
      <h6><i class="fa fa-check-circle-o"></i>&nbsp;<%= r.service %></h6>
    </div>
    <% end %>
</br></br>
  </div>

app/views/room_details/edit.html.erb
<h1>Editing Room Detail</h1>

<%= render 'form', room_detail: @room_detail %>

<%= link_to 'Show', @room_detail %> |
<%= link_to 'Back', room_details_path %>

app/views/room_details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Room Details</h1>

<table>
  <thead>
    <tr>
      <th>Hotel detail</th>
      <th>Room type</th>
      <th>Price per</th>
      <th>Bed type</th>
      <th>Room size</th>
      <th>Room view</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @room_details.each do |room_detail| %>
      <tr>
        <td><%= room_detail.hotel_detail_id %></td>
        <td><%= room_detail.room_type %></td>
        <td><%= room_detail.price_per %></td>
        <td><%= room_detail.bed_type %></td>
        <td><%= room_detail.room_size %></td>
        <td><%= room_detail.room_view %></td>
        <td><%= link_to 'Show', room_detail %></td>
        <td><%= link_to 'Edit', edit_room_detail_path(room_detail) %></td>
        <td><%= link_to 'Destroy', room_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room Detail', new_room_detail_path %>

app/views/room_details/new.html.erb
<h1>New Room Detail</h1>

<%= render 'form', room_detail: @room_detail %>

<%= link_to 'Back', room_details_path %>

app/views/room_details/services.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'room_details/services') %>");
$("#modal-window").modal();

app/views/room_details/show.html.erb
<div class="container-fluid ">
  <div class="row justify-content-center">
    <div class="col-12 col-sm-6 col-md-3">

<%= form_tag booking_details_path(user: current_user, room_id: @room_detail), class:"form-container form-group", method: :post do %>
<p>
  <strong>Hotel Name:</strong>
  <%= @hotel_details.hotel_name %>
</p>

<p>
  <strong>Room type:</strong>
  <%= @room_detail.room_type %>
</p>

<p>
  <strong>Price per:</strong>
  <%= @room_detail.price_per %>
</p>

<p>
  <strong>Bed type:</strong>
  <%= @room_detail.bed_type %>
</p>

<p>
  <strong>Room size:</strong>
  <%= @room_detail.room_size %>
</p>

<p>
  <strong>Room view:</strong>
  <%= @room_detail.room_view %>
</p>
<% if current_user && !current_user.admin? %>
  <div class="row ">
    <div class="col-12">
  

  <strong>Booking From</strong>
  <div class="form-group ">
  <%= date_field_tag :from, params[:from], placeholder: "" ,
  autofocus: true, class: "form-control form-control-lg" %>     
  </div>

  <strong>Booking Till</strong>
  <div class="form-group ">
  <%= date_field_tag :to, params[:to], placeholder: "" ,
  autofocus: true, class: "form-control form-control-lg" %>      
  </div>
  </div>
  </div>
  <%= button_tag type: :submit, class: "btn btn-success" do %>
  <%= 'Book' %>
  <% end %>

<% end %>

 <% if !current_user  %>
<%= link_to 'Login', new_user_session_path, class: "btn btn-success" %> |
<% end %>


<% if current_user && current_user.admin? %>
<%= link_to 'Edit', edit_room_detail_path(@room_detail) %> |
<% end %>
<%= link_to 'Back', hotel_detail_path(@room_detail.hotel_detail_id), class: "btn btn-primary" %>

<% end %>
</div>
</div>
</div>