config/routes.rb
Rails.application.routes.draw do
  resources :master_services
  resources :booking_details
  resources :room_details
  resources :hotel_details
  devise_for :users
  root 'hotel_details#index'  
  get 'my_bookings', to: 'users#my_bookings'
  get 'all_bookings', to: 'users#all_bookings'
  get 'services', to: 'room_details#services'
  get 'details', to: 'room_details#details'
  # get 'booking_details', to: 'users#my_booking'
end

app/views/layouts/_messages.html.erb
<% if notice %>
    <div class='alert alert-success'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <%= notice %>
    </div>
<% end %>
<% if alert %>
    <div class='alert alert-danger'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <%= alert %>
    </div>
<% end %> 

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <%= link_to 'HotelBooking', root_path, class: 'navbar-brand' %>
        <% if current_user %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <% if !current_user.admin %>
              <li class="nav-item <%= 'active' if request.path == my_bookings_path %>">
                  <%= link_to 'My Bookings', my_bookings_path, class: 'nav-link' %>
                </li>
                <% else %>
              <li class="nav-item <%= 'active' if request.path == new_hotel_detail_path %>">
                <%= link_to 'Add New Hotel Details', new_hotel_detail_path, class: 'nav-link' %>
                </li>
                <li class="nav-item <%= 'active' if request.path == master_services_path %>">
                <%= link_to 'Add New Amenities', master_services_path, class: 'nav-link' %>
                </li>
               <% end %> 
              <!-- <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li> -->
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle <%= 'active' if request.path == edit_user_registration_path %>" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Profile
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <%= link_to edit_user_registration_path, class: 'dropdown-item' do %>
                  <%= fa_icon 'edit' %> Edit profile
                  <% end %>
                </div>
              </li>
              <!-- <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
              </li> -->
            </ul>
            <ul class="navbar-nav ml-auto">
            <li class="nav-item user-name  ">
            <%= fa_icon 'user' %> <%= current_user.full_name %>
            </li>
            <li class="nav-item">
                          <%= link_to("Logout", destroy_user_session_path,
                                    class: "btn btn-danger logout-button", method: :delete)%>
            </li>
          </ul>
          </div>
          <% else %>
          <div class="collapse navbar-collapse" >
            <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                  <%= link_to("Login", new_user_session_path,
                               class: "btn btn-success login-button", method: :get)%>
            </li>
          </ul>
          </div>
        <% end %>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotelBookingWebsite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container ">
    <%= render 'layouts/messages' %>
    <div class="down-area">
    <%= yield %>
    </div>
  </div>
  </body>
</html>